=== wfwalker/birdWalker1/dtds/locations.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT locationset (location)*>

<!ELEMENT location (name | url | notes | city | state | county | latitude | longitude | system | report-url)*>

<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT notes (p)*>
<!ELEMENT p (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT system (#PCDATA)>
<!ELEMENT report-url (#PCDATA)>

=== wfwalker/birdWalker1/locations.xml
<!DOCTYPE locationset SYSTEM "file:dtds/locations.dtd"><locationset><location><name>2138 King Court</name><url></url><notes><p>in the back we have a peanut feeder, a thistle feeder, and a general purpose seed feeder</p></notes><city>Santa Clara</city><state>CA</state><county>Santa Clara</county><latitude>37.36152</latitude><longitude>121.99376</longitude><system>NAD-27</system><filename-stem>2138-king-court</filename-stem></location>
<location><name>Alviso Marina</name><url>http://santaclaracounty.org/parks/prkpages/alviso.htm</url><notes><p>the marina parking lot provides access to many miles of levees suitable for biking or walking. the open water right near the parking lot sometimes yields interesting birds.</p></notes><city>Alviso</city><state>CA</state><county>Santa Clara</county><latitude>37.42965</latitude><longitude>121.97839</longitude><system>WGS 84</system><filename-stem>alviso-marina</filename-stem></location>
<location><name>Andrew Molera</name><url>http://parks.ca.gov/central/monterey/amsp.htm</url><notes><p>you can hike in less than a mile to a campground near the beach.</p></notes><city>Monterey</city><state>CA</state><county>Monterey</county><latitude>36.272734</latitude><longitude>121.842155</longitude><system>mapblast</system><filename-stem>andrew-molera</filename-stem></location>
<location><name>Arastradero Preserve</name><url>http://www.arastradero.org/</url><city>Mountain View</city><state>CA</state><county>Santa Clara</county><latitude>37.426691</latitude><longitude>122.138925</longitude><system>mapblast</system><filename-stem>arastradero-preserve</filename-stem></location>
<location><name>Arcata Marsh</name><url>http://www.arcatacityhall.org/birding.html</url><notes><p>an amazing artificial marsh created by the City of Arcata to process its sewage.</p></notes><city>Arcata</city><state>CA</state><county>Humboldt</county><latitude></latitude><longitude></longitude><system></system><filename-stem>arcata-marsh</filename-stem></location>
<location><name>Azelea State Reserve</name><url>http://parks.ca.gov/allpages/default.asp?page_id=420</url><notes><p>a lovely park full of wild azeleas growing in forest clearings</p></notes><city>McKinleyville</city><state>CA</state><county>Humboldt</county><latitude></latitude><longitude></longitude><system></system><filename-stem>azelea-state-reserve</filename-stem></location>
<location><name>Bend Wastewater Treatment Plant</name><url></url><notes><p>Bill visited this site with Steve. Steve was checking it for a book about Oregon's sewage ponds.</p></notes><city>Bend</city><state>OR</state><county></county><latitude>44.0586</latitude><longitude>121.3142</longitude><system>Unknown</system><filename-stem>bend-wastewater-treatment-plant</filename-stem></location>
<location><name>Big Sur</name><url>http://www.bigsurcalifornia.org/</url><city>Big Sur</city><state>CA</state><county>Monterey</county><latitude></latitude><longitude></longitude><system></system><filename-stem>big-sur</filename-stem></location>
<location><name>Bodega Bay</name><url></url><city>Bodega</city><state>CA</state><county>Sonoma</county><latitude></latitude><longitude></longitude><system></system><filename-stem>bodega-bay</filename-stem></location>
<location><name>Bolinas Lagoon</name><url>http://www.marin.org/mc/pos/osdboli.html</url><city>Bolinas</city><state>CA</state><county>Marin</county><latitude>37.928</latitude><longitude>122.689</longitude><system>Unknown</system><filename-stem>bolinas-lagoon</filename-stem></location>
<location><name>Burney Falls</name><url>http://www.burneyfalls.com/pages/burnyfls.html</url><city>Burney</city><state>CA</state><county>Shasta</county><latitude>40.9066</latitude><longitude>121.6577</longitude><system>Unknown</system><filename-stem>burney-falls</filename-stem></location>
<location><name>Butte Valley Wildlife Area</name><url>http://www.buttevalleychamber.com/</url><city>Macdoel</city><state>CA</state><county>Siskiyou</county><latitude>41.6701</latitude><longitude>121.8749</longitude><system>Unknown</system><filename-stem>butte-valley-wildlife-area</filename-stem></location>
<location><name>Calero Reservoir</name><url>http://claraweb.co.santa-clara.ca.us/parks/prkpages/calero.htm</url><notes><p>A reservoir south of San Jose, said to be a reliable spot for Bald Eagles</p><p></p><p></p></notes><city>San Jose</city><state>CA</state><county>Santa Clara</county><latitude>37.2016</latitude><longitude>121.82835</longitude><system>mapblast</system><filename-stem>calero-reservoir</filename-stem></location>
<location><name>Carmel</name><url></url><city>Carmel</city><state>CA</state><county>Monterey</county><latitude></latitude><longitude></longitude><system></system><filename-stem>carmel</filename-stem></location>
<location><name>Champaign County</name><url>http://www.web-makers.com/Audubon/</url><city>Champaign</city><state>IL</state><county>Champaign</county><latitude>40.113</latitude><longitude>88.264949</longitude><system></system><filename-stem>champaign-county</filename-stem></location>
<location><name>Charleston Slough</name><url>http://www.calmanac.com/paw/paonline/things_do/baylands.shtml</url><notes><p>Our most visited and most productive site.</p></notes><city>Palo Alto</city><state>CA</state><county>Santa Clara</county><latitude>37.461</latitude><longitude>122.115</longitude><system>mapblast</system><filename-stem>charleston-slough</filename-stem></location>
<location><name>Chez Frankel</name><url></url><notes><p>Between Gorda and Ragged Point</p></notes><city>Big Sur</city><state>CA</state><county>Monterey</county><latitude>35.83825</latitude><longitude>121.39863</longitude><system>WGS 84</system><filename-stem>chez-frankel</filename-stem></location>
<location><name>China Camp State Park</name><url></url><city>San Rafael</city><state>CA</state><county>Marin</county><latitude></latitude><longitude></longitude><system></system><filename-stem>china-camp-state-park</filename-stem></location>
<location><name>Colusa NWR</name><url>http://www.r1.fws.gov/sacnwrc/</url><city>Colusa</city><state>CA</state><county>Colusa</county><latitude>39.2396</latitude><longitude>122.0742</longitude><system>Unknown</system><filename-stem>colusa-nwr</filename-stem></location>
<location><name>Coyote Creek County Park</name><url></url><city>San Jose</city><state>CA</state><county>Santa Clara</county><latitude></latitude><longitude></longitude><system></system><filename-stem>coyote-creek-county-park</filename-stem></location>
<location><name>Coyote Creek Field Station</name><url>http://www.sfbbo.org/ccfs01.html</url><notes><p>Formerly the Coyote Creek Riparian Station, now part of the San Francisco Bay Bird Observatory</p><p></p><p></p></notes><city>Alviso</city><state>CA</state><county>Santa Clara</county><latitude>37.420236</latitude><longitude>121.987878</longitude><system>mapblast</system><filename-stem>coyote-creek-field-station</filename-stem></location>
<location><name>Coyote Hills</name><url>http://www.ebparks.org/parks/coyote.htm</url><notes><p>a great place for flying RC gliders. There's also a lovely boardwalk and some golden hills for walking on</p></notes><city>Fremont</city><state>CA</state><county>Alameda</county><latitude>37.55058</latitude><longitude>122.08602</longitude><system>WGS 84</system><filename-stem>coyote-hills</filename-stem></location>
<location><name>Coyote Point Marina</name><url>http://www.cpyc.com/</url><notes><p>First visited here with Steve Shunk  in January 2001.</p></notes><city>Burlinghame</city><state>CA</state><county>San Mateo</county><latitude>37.567</latitude><longitude>122.3669</longitude><system>Unknown</system><filename-stem>coyote-point-marina</filename-stem></location>
<location><name>Crown Memorial State Beach</name><url>http://www.parks.ca.gov/allpages/default.asp?page_id=526</url><city>Alameda</city><state>CA</state><county>Alameda</county><latitude></latitude><longitude></longitude><system></system><filename-stem>crown-memorial-state-beach</filename-stem></location>
<location><name>Don Edwards Center</name><url>http://www.r1.fws.gov/sfbnwr/default.htm</url><city>Alviso</city><state>CA</state><county>Santa Clara</county><latitude>37.43269</latitude><longitude>121.96244</longitude><system>WGS 84</system><filename-stem>don-edwards-center</filename-stem></location>
<location><name>Drawbridge</name><url>http://www.slip.net/~bobk/</url><notes><p>An abandoned town along the amtrak tracks in the marshes of Fremont. We got to go there during a San Jose christmas bird count</p><p></p></notes><city>Fremont</city><state>CA</state><county>Santa Clara</county><latitude>37.466389</latitude><longitude>121.973889</longitude><system>mapblast</system><filename-stem>drawbridge</filename-stem></location>
<location><name>Ed Levin State Park</name><url>http://santaclaracounty.org/parks/prkpages/levndch.htm</url><notes><p></p><p>Lat: 37.445855 Lon: -121.857762</p></notes><city>Milpitas</city><state>CA</state><county>Santa Clara</county><latitude>37.445855</latitude><longitude>121.857762</longitude><system>mapblast</system><filename-stem>ed-levin-state-park</filename-stem></location>
<location><name>Elkhorn Slough</name><url>http://www.elkhornslough.org/</url><notes><p>a lovely estuary south of Santa Cruz. Unfortunately, the slough's limited access hours have prevented us from exploring it in depth.</p></notes><city>Santa Cruz</city><state>CA</state><county>Monterey</county><latitude>36.804444</latitude><longitude>121.785833</longitude><system>mapblast</system><filename-stem>elkhorn-slough</filename-stem></location>
<location><name>Filoli</name><url></url><city>Meno Park</city><state>CA</state><county>San Mateo</county><latitude></latitude><longitude></longitude><system></system><filename-stem>filoli</filename-stem></location>
